function [x_eq,u_eq] = LiftEquilibrium(dc,dw,BuildingHeight,Jp,Jm,LinearDamping,LinearStiffness,Mc,MotorViscousFriction,Mw,Rp,g,mu,gearbox,min_length,K0,C0,state9)
%LiftEquilibrium
%    [X_EQ,U_EQ] = LiftEquilibrium(DC,DW,BuildingHeight,Jp,Jm,LinearDamping,LinearStiffness,Mc,MotorViscousFriction,Mw,Rp,G,MU,GEARBOX,MIN_LENGTH,K0,C0,STATE9)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 12:18:26

%Version: 1.0
mt1 = [((LinearStiffness.*dw.*4.0-BuildingHeight.*K0.*LinearStiffness.*2.0+LinearStiffness.*Mw.*g.*4.0+K0.*dw.*min_length.*2.0+K0.*g.*min_length.^2.*mu+K0.*Mw.*g.*min_length.*2.0+LinearStiffness.*g.*min_length.*mu.*2.0+K0.*LinearStiffness.*Rp.*gearbox.*state9.*2.0+K0.*Rp.*dw.*gearbox.*state9.*2.0+K0.*Mw.*Rp.*g.*gearbox.*state9.*2.0+LinearStiffness.*Rp.*g.*gearbox.*mu.*state9.*2.0+K0.*Rp.^2.*g.*gearbox.^2.*mu.*state9.^2+K0.*Rp.*g.*gearbox.*min_length.*mu.*state9.*2.0).*(-1.0./2.0))./(K0.*LinearStiffness);0.0];
mt2 = [((LinearStiffness.*dw.*2.0-BuildingHeight.*K0.*LinearStiffness.*2.0+LinearStiffness.*Mw.*g.*2.0-K0.*LinearStiffness.*min_length+K0.*dw.*min_length+K0.*g.*min_length.^2.*mu+K0.*Mw.*g.*min_length+LinearStiffness.*g.*min_length.*mu.*2.0+K0.*LinearStiffness.*Rp.*gearbox.*state9+K0.*Rp.*dw.*gearbox.*state9+K0.*Mw.*Rp.*g.*gearbox.*state9+LinearStiffness.*Rp.*g.*gearbox.*mu.*state9.*2.0+K0.*Rp.^2.*g.*gearbox.^2.*mu.*state9.^2+K0.*Rp.*g.*gearbox.*min_length.*mu.*state9.*2.0).*(-1.0./2.0))./(K0.*LinearStiffness);0.0];
mt3 = [((LinearStiffness.*dc.*2.0-BuildingHeight.*K0.*LinearStiffness+LinearStiffness.*Mc.*g.*2.0-K0.*LinearStiffness.*min_length+K0.*dc.*min_length+K0.*g.*min_length.^2.*mu+BuildingHeight.*LinearStiffness.*g.*mu.*2.0+K0.*Mc.*g.*min_length+LinearStiffness.*g.*min_length.*mu.*2.0-K0.*LinearStiffness.*Rp.*gearbox.*state9+BuildingHeight.*K0.*g.*min_length.*mu+K0.*Rp.*dc.*gearbox.*state9+K0.*Mc.*Rp.*g.*gearbox.*state9-LinearStiffness.*Rp.*g.*gearbox.*mu.*state9.*2.0-K0.*Rp.^2.*g.*gearbox.^2.*mu.*state9.^2+BuildingHeight.*K0.*Rp.*g.*gearbox.*mu.*state9).*(-1.0./2.0))./(K0.*LinearStiffness);0.0];
mt4 = [((LinearStiffness.*dc.*4.0+LinearStiffness.*Mc.*g.*4.0+K0.*dc.*min_length.*2.0+K0.*g.*min_length.^2.*mu+BuildingHeight.*LinearStiffness.*g.*mu.*2.0+K0.*Mc.*g.*min_length.*2.0+LinearStiffness.*g.*min_length.*mu.*2.0-K0.*LinearStiffness.*Rp.*gearbox.*state9.*2.0+BuildingHeight.*K0.*g.*min_length.*mu+K0.*Rp.*dc.*gearbox.*state9.*2.0+K0.*Mc.*Rp.*g.*gearbox.*state9.*2.0-LinearStiffness.*Rp.*g.*gearbox.*mu.*state9.*2.0-K0.*Rp.^2.*g.*gearbox.^2.*mu.*state9.^2+BuildingHeight.*K0.*Rp.*g.*gearbox.*mu.*state9).*(-1.0./2.0))./(K0.*LinearStiffness);0.0;state9;0.0];
x_eq = [mt1;mt2;mt3;mt4];
if nargout > 1
    u_eq = Rp.*gearbox.*(dc-dw+Mc.*g-Mw.*g+BuildingHeight.*g.*mu-Rp.*g.*gearbox.*mu.*state9.*2.0);
end
